### ISSUE TITLE
Too low household count for high density residential building

### ISSUE THREAD

**Issue by Vectorial1024** [algernon-A/Realistic-Population-Revisited#34]
For example:

![Screenshot](https://user-images.githubusercontent.com/17726797/159427631-678721b7-cf6c-4d31-b7ff-c104ba04f3d1.png)

This is a 1x1 environmentally-friendly high-density residential from the Green Cities DLC.

Even when there are multiple floors to this high-density residential building, each floor is unable to generate any household due to low floor size, and so the entire multi-story residential building only has 1 household, which is strange.

**Comment by algernon-A** [comment]
That's because the mod's calcuations are based on real-world figures, and that's not a real-world building.

For fantasy buildings like that one, it's up to the user to override the settings to whatever they feel is appropriate, using either a custom calculation pack (the multi-floor unit flag possibly has a use case here, depending on user preference), or just a simple manual override.
